import type { AnamnesisFormData } from "@/shared";

export const getDefaultValues = (): AnamnesisFormData => ({
  fullName: "",
  birthDate: "",
  gender: undefined,
  notes: {},
  primaryExam: { reason: "", suspectedDiagnosis: undefined },
  type1Diabetes: null,
  type2Diabetes: null,
  therapy: {
    currentDrugs: [{ name: "", dose: "" }],
    basalInsulin: [{ name: "", dose: "" }],
    prandialInsulin: [{ name: "", dose: "" }],
    carbCounting: null,
    carbRatio: "",
    injectionSites: "",
    lipohypertrophy: null,
  },
  hypoglycemia: {
    frequencyPerWeek: null,
    severeEpisodes: null,
    severeEpisodesCount: null,
    severeEpisodesWhen: "",
    severeEpisodesClinic: "",
    awarenessPreserved: null,
    provokingFactors: {
      physicalActivity: false,
      missedMeal: false,
      alcohol: false,
    },
    hasGlucagon: null,
    familyTrained: null,
    nocturnalHypoglycemia: null,
  },
  selfMonitoring: {
    frequency: "",
    sameTime: null,
    ifNotSameTimeReason: "",
    diary: null,
  },
  complications: {
    eyes: {
      visionLoss: null,
      visionLossStart: "",
      visionLossDuration: "",
      nightVisionGood: null,
      lastFundusExamDate: "",
    },
    nose: { snoring: null },
    ears: {
      hearingLoss: null,
      hearingLossStart: "",
      hearingLossDuration: "",
      lastEntExamDate: "",
    },
    gastrointestinal: {
      gastritis: null,
      ulcers: null,
      abdominalPainAfterEating: null,
      stoolFrequency: "",
      stoolConsistency: 5,
    },
    urinary: { kidneyStones: null },
    nephropathy: { albuminCreatinine: "", gfr: "" },
    neuropathy: {
      symptoms: { numbness: false, pain: false, paresthesia: false },
      numbnessTime: "",
      paresthesiaType: {
        crawling: false,
        shots: false,
        allodynia: false,
        hyperalgesia: false,
        nightCramps: false,
        numbness: false,
        burning: false,
      },
      coldFeet: null,
      howWarmFeet: "",
      feetToRadiator: null,
      amputations: null,
      amputationLevel: "",
      amputationDate: "",
      footSkin: "",
      hyperkeratosisDegree: "",
      footTemperature: "",
      footColor: "",
      nails: "",
      footDeformity: "",
      lowerLegs: "",
      halluxValgus: null,
      hammerToe: null,
      clawToe: null,
      digitusSuperductus: null,
      sensitivity: {
        vibration: { right: null, left: null },
        temperature: { right: null, left: null },
        pain: { right: null, left: null },
        tactile: { right: null, left: null },
        jointMuscle: { right: null, left: null },
        achillesReflex: { right: null, left: null },
        kneeReflex: { right: null, left: null },
      },
      veins: {
        norm: { right: false, left: false },
        telangiectasia: { right: false, left: false },
        varicoseVeins: { right: false, left: false },
        edema: { right: false, left: false },
        lipodermatosclerosis: { right: false, left: false },
        healingUlcer: { right: false, left: false },
        activeUlcer: { right: false, left: false },
      },
      lymphedema: null,
      lymphedemaStage: {
        stageI: { right: false, left: false },
        stageII: { right: false, left: false },
        stageIII: { right: false, left: false },
        stageIV: { right: false, left: false },
      },
      lasegueSymptom: "",
      lasegueSide: "",
      lasegueDetails: "",
      footExamNotes: "",
      woundAppearance: "",
    },
  },
  examination: {
    cardiovascularEvents: "",
    bloodPressure: "",
    otherChronicDiseases: "",
    currentMedications: "",
    allergies: "",
    hospitalizations: "",
    vaccinations: "",
    thyroidDisease: null,
    celiacDisease: null,
    otherAutoimmune: "",
    familyHistory: "",
    pregnancies: null,
    births: null,
    menstrualCycle: "",
  },
  lifestyle: {
    alcoholFrequency: "",
    alcoholType: "",
    smoking: null,
    smokingStartAge: null,
    cigarettesPerDay: null,
    saltFood: null,
    processedFood: null,
    coffeeCupsPerDay: null,
    strongCoffee: null,
    energyDrinks: null,
    occupation: "",
    sedentaryWork: null,
    stress: null,
  },
  measurements: {
    pulseOximetry: { leftHand: null, rightHand: null },
    pulsePalpation: {
      radialArtery: { rhythm: "", symmetry: "" },
      posteriorTibialArtery: { left: null, right: null },
      dorsalisPedisArtery: { left: null, right: null },
    },
    conditionsMet: null,
    bpArms: {
      leftSystolic: null,
      leftDiastolic: null,
      rightSystolic: null,
      rightDiastolic: null,
    },
    pulsePressure: null,
    bpLegs: {
      leftSystolic: null,
      leftDiastolic: null,
      rightSystolic: null,
      rightDiastolic: null,
    },
    abiIndex: { left: null, right: null },
    legPainWalking: null,
    painStopsAfterRest: null,
    walkingDistance: "",
    limbColor: "",
    limbTemperature: "",
    limbSkin: "",
    bpRepeat: {
      leftSystolic: null,
      leftDiastolic: null,
      rightSystolic: null,
      rightDiastolic: null,
    },
  },
  secondaryHypertension: {
    nsaidsFrequency: "",
    decongestantsFrequency: "",
    otherDrugs: "",
    hyperaldosteronism: {
      polydipsiaPolyuria: null,
      muscleWeakness: null,
      limbCramps: null,
      constipation: null,
    },
    frequentHeadaches: null,
    stroke: null,
    tia: null,
    tiaDetails: "",
    pheochromocytoma: {
      stableOrCrisis: "",
      profuseSweating: null,
      coldExtremities: null,
      arrhythmias: null,
    },
    hypercortisolism: {
      centralObesity: null,
      moonFace: null,
      cheekFlush: null,
      buffaloHump: null,
      bruises: null,
      proximalWeakness: null,
      striae: null,
      newDiabetes: null,
      amenorrhea: null,
    },
    osas: {
      nightSnoring: null,
      nightAwakenings: null,
      nocturia: null,
      daytimeSleepiness: null,
      obesity: null,
    },
    familyHistory: {
      hypertension: null,
      earlyHeartAttackStroke: null,
      pheochromocytoma: null,
    },
    pregnancyHypertension: null,
  },
  heartFailure: {
    urineColorChange: null,
    urineColor: "",
    chestPain: null,
    chestPainTrigger: "",
    radiatesToLeftArm: null,
    relievesWithNitroglycerin: null,
    frequentAttacks3Months: null,
    dyspneaOnExertion: null,
    dyspneaFunctionalClass: "",
    takesTicagrelor: null,
    smallCircle: {
      pillowsForSleep: null,
      forcedPosition: null,
      nightDyspnea: null,
      acrocyanosis: { nasolabialTriangle: false, hands: false, feet: false },
      saturation: null,
    },
    bigCircle: {
      legEdema: null,
      tightShoes: null,
      edemaOnset: "",
      symmetric: null,
      localization: "",
      timeOfDay: "",
      edemaImprovesNight: null,
      edemaImprovesElevation: null,
      edemaTemperature: "",
      edemaColor: "",
      edemaDensity: "",
      pittingEdema: null,
      edemaResolves: "",
      painful: null,
      takesNifedipineAmlodipineNsaids: null,
    },
    hepatomegaly: {
      rightHypochondriumPain: null,
      liverSize: "",
      liverEdge: "",
      liverPainful: null,
      hepaticPulsation: null,
      hepatojugularReflux: null,
    },
    jugularVeins: { onInspirationAndExpiration: null, onlyOnInspiration: null },
    nyhaClass: "",
  },
  h2fpef: {
    obesityBMI30: false,
    hypertension2Drugs: false,
    atrialFibrillation: false,
    pulmonaryHypertension: false,
    pulmonaryHypertensionValue: null,
    elderly60: false,
    fillingPressure: false,
    fillingPressureValue: null,
    totalScore: 0,
  },
  additionalHistory: {
    myocardialInfarction: "",
    coronaryAngiography: "",
    stenting: "",
    surgeries: "",
    appendicitis: "",
    cholecystitis: "",
    tuberculosis: "",
    hiv: "",
    hepatitis: "",
    syphilis: "",
    covidYear: "",
    allergies: { what: "", how: "", angioedema: null },
    travelOutsideRF: null,
    contactWithPatients: null,
    insectAnimalBites: null,
    weight: null,
    height: null,
    abdominalCircumference: null,
  },
});
